In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [2]:
!nvidia-smi

Sun Apr 14 10:25:23 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Pytorch Tensors

#### Create Tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Scalars dont have a dimention
scalar.ndim

0

In [5]:
# we can use .item() to get the integer value of that tensor
scalar.item()

7

#### Create a vector

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

####  Create a MATRIX

In [9]:
MATRIX = torch.tensor([[7, 8],
                       [5, 4]])
MATRIX

tensor([[7, 8],
        [5, 4]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

# create a TENSOR

In [12]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [6, 7, 8]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

In [16]:
TENSOR[0][1]

tensor([4, 5, 6])

# Create Random Tensors

In [17]:
# torch.manual_seed(42)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2685, 0.5822, 0.3274, 0.4165],
        [0.0189, 0.3139, 0.6368, 0.8472],
        [0.6937, 0.8383, 0.9538, 0.0278]])

In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

#### Create a random image tensor

In [20]:
ran_img_tensor = torch.rand(size=(224, 224, 3))
ran_img_tensor

tensor([[[0.6778, 0.1779, 0.6400],
         [0.9538, 0.3318, 0.4025],
         [0.6151, 0.1344, 0.9615],
         ...,
         [0.8477, 0.1981, 0.8839],
         [0.4216, 0.5868, 0.0581],
         [0.8844, 0.2110, 0.0953]],

        [[0.1172, 0.5266, 0.8632],
         [0.8491, 0.1225, 0.9475],
         [0.7050, 0.9461, 0.6353],
         ...,
         [0.8935, 0.1972, 0.2214],
         [0.0365, 0.7920, 0.4486],
         [0.8255, 0.3359, 0.6251]],

        [[0.1666, 0.9845, 0.8827],
         [0.9556, 0.1396, 0.6749],
         [0.7208, 0.4539, 0.6129],
         ...,
         [0.2270, 0.9491, 0.9484],
         [0.5053, 0.3519, 0.2273],
         [0.3250, 0.5817, 0.3501]],

        ...,

        [[0.2509, 0.2413, 0.2569],
         [0.1296, 0.4388, 0.3958],
         [0.1589, 0.8188, 0.0208],
         ...,
         [0.3092, 0.8865, 0.2570],
         [0.0854, 0.1093, 0.8698],
         [0.1847, 0.2078, 0.2134]],

        [[0.9496, 0.2718, 0.6947],
         [0.8294, 0.7980, 0.7794],
         [0.

In [21]:
ran_img_tensor.ndim

3

In [22]:
ran_img_tensor.shape

torch.Size([224, 224, 3])

# Zero and onces Tensors

In [23]:
zero_tensors = torch.zeros(size=(3, 4))
zero_tensors

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones_tensor = torch.ones(size=(3, 4))
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Create Range of tensors and tensor like

#### Range tensor

In [25]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
two_to_255 = torch.arange(start=2, end=255, step=5)
two_to_255

tensor([  2,   7,  12,  17,  22,  27,  32,  37,  42,  47,  52,  57,  62,  67,
         72,  77,  82,  87,  92,  97, 102, 107, 112, 117, 122, 127, 132, 137,
        142, 147, 152, 157, 162, 167, 172, 177, 182, 187, 192, 197, 202, 207,
        212, 217, 222, 227, 232, 237, 242, 247, 252])

#### Tensors like

In [27]:
alike_tensor = torch.zeros_like(input=two_to_255)
alike_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])

In [28]:
alike_tensor2 = torch.ones_like(input=two_to_255)
alike_tensor2

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1])

# Tensor Data types

#### Float32 tensor

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_32_tensor.dtype   # even with dtype = None we get float32 because the default data type of a tensor in pytorch is float 32

torch.float32

In [31]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
float_16_tensor.dtype

torch.float16

# Tensors with device and requires_grad

In [33]:
new_tensor = torch.rand([3, 3, 3],dtype=torch.float16, device=None, requires_grad=True)
new_tensor

tensor([[[0.2720, 0.8970, 0.4434],
         [0.8721, 0.2510, 0.3096],
         [0.2568, 0.0913, 0.1685]],

        [[0.2920, 0.9712, 0.1616],
         [0.2954, 0.8179, 0.2275],
         [0.0425, 0.2422, 0.2290]],

        [[0.7812, 0.1001, 0.9712],
         [0.5518, 0.7153, 0.7773],
         [0.3672, 0.5103, 0.8008]]], dtype=torch.float16, requires_grad=True)

In [34]:
# device = what device is our tensor on
# requires_grad = if you want pytorch to track the gradiant for future cacluations we can use this

# Getting Tensor Attributes

In [35]:
new_tensor.device

device(type='cpu')

In [36]:
new_tensor.requires_grad

True

In [37]:
new_tensor.shape

torch.Size([3, 3, 3])

In [38]:
new_tensor.ndim

3

# Matrix Manipulating

In [39]:
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                        [5, 6]])

tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [40]:
tensor_a, tensor_b

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [41]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# finding min max meanv and sum


In [42]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
# Find max
torch.max(x)

tensor(90)

In [44]:
# Find min
torch.min(x)

tensor(0)

In [45]:
# find sum
torch.sum(x)

tensor(450)

In [46]:
# Find mean
torch.mean(x.type(torch.float))

tensor(45.)

# Min max Position

In [47]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
torch.argmin(x)

tensor(0)

In [49]:
torch.argmax(x)

tensor(9)

# Reshape, stacking, squeesing, unsqueezing and view tensors3


* Squeeze - remove all the `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a tensor
* permute - Swaped the dimension of a tensor and return


In [50]:
tensor_x = torch.arange(1., 10.)
tensor_x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [51]:
tensor_x.shape

torch.Size([9])

In [52]:
tensor_x.ndim

1

In [53]:
x_reshaped = tensor_x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [54]:
x_reshaped2 = tensor_x.reshape(1,9)
x_reshaped2

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
x_reshaped3 = tensor_x.reshape(9,1)
x_reshaped3

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

#### View

In [56]:
z = tensor_x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
# View of the tensor share the same memory as the original input therefore if we change the view . the original will change too

#### Stack

In [58]:
x_stacked = torch.stack([tensor_x,tensor_x,tensor_x,tensor_x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [59]:
x_stacked.shape

torch.Size([4, 9])

In [60]:
x_stacked = torch.stack([tensor_x,tensor_x,tensor_x,tensor_x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [61]:
x_stacked.shape

torch.Size([9, 4])

#### Squeeze

In [62]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
x_reshape = x.reshape(1, 9)
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [64]:
x_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [65]:
y = torch.arange(1., 10.)
y

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [66]:
y_reshape = y.reshape(9, 1)
y_reshape

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [67]:
y_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### Unsqueeze()

In [68]:
# unsqueeze will add a single dimension to a specific dim

In [69]:
y = torch.arange(1., 10.)
y

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [70]:
y_reshape = y.reshape(9, 1)
y_reshape

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [71]:
y_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [72]:
y_reshape.unsqueeze(dim=0)

tensor([[[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

#### permute

In [73]:
# This will return a view

In [74]:
x = torch.randn(2, 3, 5)
x

tensor([[[-0.3670, -0.2184,  0.2902,  0.3657, -1.4701],
         [-1.6750, -0.1775, -1.7455, -0.1135, -0.5931],
         [-0.2744, -0.4651, -0.4875,  0.3449,  0.4206]],

        [[ 1.7803, -1.9317,  0.0179, -0.4483,  0.6316],
         [-1.4989, -0.7376, -0.9272,  1.1864, -0.3176],
         [ 0.8029,  0.1905,  0.0262,  0.7874,  0.4664]]])

In [75]:
x.size()

torch.Size([2, 3, 5])

In [76]:
torch.permute(x,(2, 0, 1))

tensor([[[-0.3670, -1.6750, -0.2744],
         [ 1.7803, -1.4989,  0.8029]],

        [[-0.2184, -0.1775, -0.4651],
         [-1.9317, -0.7376,  0.1905]],

        [[ 0.2902, -1.7455, -0.4875],
         [ 0.0179, -0.9272,  0.0262]],

        [[ 0.3657, -0.1135,  0.3449],
         [-0.4483,  1.1864,  0.7874]],

        [[-1.4701, -0.5931,  0.4206],
         [ 0.6316, -0.3176,  0.4664]]])

# Access GPU in pytorch

In [77]:
!nvidia-smi

Sun Apr 14 10:28:56 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#### Check for GPU access using Pytorch

In [79]:
torch.cuda.is_available()

True

In [80]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [81]:
device

'cuda'

In [82]:
# Count the number of devices
torch.cuda.device_count()

1

#### Puting tensors and models into GPU

In [85]:
# Create a tensor
tensor = torch.tensor([1, 2, 3, 4, 5], device='cpu')
tensor

tensor([1, 2, 3, 4, 5])

In [86]:
tensor.device

device(type='cpu')

In [88]:
# put the tensor to GPU if avaliable
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4, 5], device='cuda:0')

In [90]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [92]:
# Move the tensor back to CPU
tensor_to_cpu = tensor_on_gpu.to('cpu')
tensor_to_cpu

tensor([1, 2, 3, 4, 5])

In [93]:
tensor_to_cpu.device

device(type='cpu')

In [94]:
# If the tensors are on GPU we cant transform them into NumPy. we need to send the tensors back to CPU